### ISSUE TITLE
get content question

### ISSUE THREAD

**Issue by Bickson** [flamelink/flamelink-js-sdk#100]
Hi, is it possible to get content based on attribute in referenced schema?
say I want all my products based on category and my product schema has reference to category schema.
Sorry if i explain poorly!

Thanks!

**Comment by jperasmus** [comment]
I haven't checked now, but it depends on the order in which we populate the references and applying the filters.

You can try to write your query like this:

```
const result = await app.content.get({
	schemaKey: 'yourSchema',
	populate: true, // to expand the references
	filters: [
		['_fl_meta_.schema.category', '==', 'someValue'] // assuming the field is called "category"
	]
})
```

**Comment by Bickson** [comment]
hmm... doesn't seem to work.
products have a field called category which is a reference to schema category that have a name.
can I get product dependent on category name?

**Comment by gitdubz** [comment]
Hi @Bickson I am not sure if you have managed to resolve the issue yet but you can try this

const result = await app.content.get({
	schemaKey: 'yourSchema',
	populate: true, // to expand the references
	filters: [
		['category', '==', 'someValue'] // assuming the field is called "category"
	]
})

**Comment by erik-slack** [comment]
@gitdubz that was very helpful!  I don't see it in the documentation though.  Can it be updated?

https://flamelink.github.io/flamelink-js-sdk/#/content?id=subscribe

**Comment by gitdubz** [comment]
@erik-slack @Bickson 

Documentation for using filters have been added for both relational and non relational values.
Please see (sections including `filters`)
- https://flamelink.github.io/flamelink-js-sdk/#/content?id=get 
- https://flamelink.github.io/flamelink-js-sdk/#/content?id=subscribe


and
