### ISSUE TITLE
Flamelink is slow to respond when "populate: true"

### ISSUE THREAD

**Issue by marciliocarvalho** [flamelink/flamelink-js-sdk#104]
When "populate: true", image URLs take too long to return, delaying site display by 6 seconds.

Would there be a way to decrease this delay?

**Comment by gitdubz** [comment]
Hi @marciliocarvalho,

What version of the SDK are you using?

Also could you kindly paste a code snippet of the query please?

**Comment by marciliocarvalho** [comment]
`this.spinner.show()

    this.flamelink.content.get({
      schemaKey: 'sobre',
      populate: true
    }).then(result => {
      console.log(result)
      this.dados = result
    }).finally(() => {
      this.spinner.hide()
    })`

**Comment by gitdubz** [comment]
Do you have any other relational fields for your `sobre` schema?

**Comment by marciliocarvalho** [comment]
Within "sobre", the relational fields that exist are images

**Comment by marciliocarvalho** [comment]
when I put "populate: false" the site loads very fast but without the images

**Comment by gitdubz** [comment]
thanks, and what version are you using?

I know there were some performance issues on earlier versions.

**Comment by marciliocarvalho** [comment]
1.0.0-alpha.26

**Comment by marciliocarvalho** [comment]
"angular-flamelink": "0.0.7"

**Comment by gitdubz** [comment]
and you flamelink version? if it is `flamelink@next` consider removing this and installing it again

**Comment by marciliocarvalho** [comment]
but which version should i install?

**Comment by gitdubz** [comment]
Oh sorry just saw your comment on the flamelink version

**Comment by marciliocarvalho** [comment]
but which version should i install?

**Comment by gitdubz** [comment]
the latest version is fine which seems is what you have.

you can try the following
`this.flamelink.content.get({
  schemaKey: 'sobre',
  populate: { 
    field: 'images', 
    size: { 
        width: 1920, 
        height: 999, 
        quality: 1 
    }
 }
}).then(result => {
  console.log(result)
  this.dados = result
}).finally(() => {
  this.spinner.hide()
})`

you can change the image height and width and quality to what you need 
but it needs to correspond to your settings in flamelink

**Comment by marciliocarvalho** [comment]
ok, I uninstalled flamelink @ next and tried to install flamelink only, in its stable version. But the installation gave error.

**Comment by gitdubz** [comment]
This version should work  "flamelink": "^1.0.0-alpha.26"

The stable version does not support cloud firestore and will be replaced with the new version soon.

If the integration with flamelink@next does not work, perhaps log an issue on the `angular-flamelink` repository. We do not own that repository but the developer who does is helpful and will most likely updated it fairly quickly.

**Comment by marciliocarvalho** [comment]
OK thank you

However, I used Flamelink with Angular without using angular-flamelink, using JavaScript directly, and the delay problem continued.

So I imagine the problem is not in angular-flamelink, you know?

**Comment by gitdubz** [comment]
I had a look at the angular-flamelink repo and it seems like it uses the latest flamelink-sdk under the hood, so would not be the issue (was more referring to the integration with specific versions of the flamelink-sdk)

Have you tried this 

```
this.flamelink.content.get({
  schemaKey: 'sobre',
  populate: { 
    field: 'images', 
    size: { 
        width: 1920, 
        height: 999, 
        quality: 1 
    }
 }
}).then(result => {
  console.log(result)
  this.dados = result
}).finally(() => {
  this.spinner.hide()
})```

**Comment by marciliocarvalho** [comment]
It worked! Thank you!

**Comment by namabrijraj** [comment]
Hi @gitdubz 

i'm getting data with populate:true but getting failed with polulate:false
