### ISSUE TITLE
How to populate second-level relational field.

### ISSUE THREAD

**Issue by ribalnasr** [flamelink/flamelink-js-sdk#115]
hi i have a collection of **projects**, each project has a relational field of multiple **partners** and each partner has a **logo** image.

the final result i expect is as follows:

```ts 
[
	{
		title: 'Project title',
		partners: [
			{
				name: 'First Partner',
				logo: [{
					// ...
					url: 'url_to_image'
				}]
			}
		]
	}
]
```

i'm try the following query
```ts
.subscribe({
	schemaKey: 'projects',
	populate: ['partners']
})
```

but the above populate only the partner level and returns the logo as a document reference:

```ts 
[
	{
		title: 'Project title',
		partners: [
			{
				name: 'First Partner',
				logo:[DocumentReference]
			}
		]
	}
]
```

any suggestions?

**please note that using populate:true is out of question** since it conflicts with my firestore rules, i need to explicit specify each field i need to populate.

**Comment by ribalnasr** [comment]
nevermind... i finally found that in your docs: https://flamelink.github.io/flamelink-js-sdk/#/api-overview?id=fields

**solution:**
```ts
.subscribe({
	schemaKey: 'projects',
	populate: [{
		field: 'partners',
		fields: ['name', 'logo'],
		populate: ['logo']
	}]
})
```

**Comment by jperasmus** [comment]
Thanks, sorry, I missed this issue when it came in. Glad you got it working.
