### ISSUE TITLE
populate true fails in relational inside repeater

### ISSUE THREAD

**Issue by wollowizard** [flamelink/flamelink-js-sdk#128]
I create a single schema, inside I put a field group, inside that a repeater and inside a relational select.
populate:true does not populate the select. Is this a known limitation?

**Comment by jperasmus** [comment]
This is definitely a known issue we picked up in the app itself and has been fixed. It will be released within the next ~week or 2. It has actually been fixed in December already but placed in an upcoming test environment.

**Comment by jperasmus** [comment]
Hi @wollowizard this should be fixed in the app now. You will have to resave the entries with nested relational fields so that the correct document references can be written to Firestore.

**Comment by wollowizard** [comment]
> Hi @wollowizard this should be fixed in the app now. You will have to resave the entries with nested relational fields so that the correct document references can be written to Firestore.

That is indeed fixed! thanks a lot

**Comment by jperasmus** [comment]
Excellent! Thanks for confirming
