### ISSUE TITLE
Not working server-side with Firebase admin & functions

### ISSUE THREAD

**Issue by ribalnasr** [flamelink/flamelink-js-sdk#136]
I've been trying to get flamelink to work in a firebase function with no success. the result has no error but returns undefined, here's my code:

```ts
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
const firebaseApp = admin.initializeApp();

import flamelink from 'flamelink/app';

import 'flamelink/content';

const flApp = flamelink({
	firebaseApp,
	dbType: 'cf',
	env: 'production',
	locale: 'en-US',
});

export const testFunction = functions.https.onRequest((request, response) => {
	flApp.content.get({
		schemaKey: 'projects'
	}).then(
		(res: any) => {
			console.log(res) // This return 'undefined'
			response.send(res)
		}
	).catch(
		(error: any) => response.send(error)
	)
});
```

Help please.. been stuck on this for days.

**Comment by dewetvdm** [comment]
Hi @ribalnasr 

Does this work if you run it server-side as opposed to a cloud function?

I will have a look at it and see if I can reproduce it within a cloud function.

**Comment by ribalnasr** [comment]
i haven't tried that. i usually only work server-side within a firebase
project. i will try to reproduce it with node as soon as i can. meanwhile
awaiting your reply

**Comment by ribalnasr** [comment]
i just tried outside firebase and it's working! any updates from your side?

**Comment by Neilpoulin** [comment]
I use Flamelink in Firebase Cloud Functions and don't have any issues. I noticed that in my setup, I'm importing Flamelink like this, vs what you shared

```typescript
// How my app is set up
import * as flamelink from "flamelink/app";

// your example
import flamelink from 'flamelink/app';
```

You also may need to get your admin app using the `admin.app()` function, rather than the return of `admin.initializeApp` - at least that's how my code has been running for months. See below. 

```typescript
import * as admin from "firebase-admin";

admin.initializeApp();
const firebaseApp = admin.app();
// then initialize flamelink like you had

```

**Comment by dewetvdm** [comment]
Thanks @Neilpoulin I think that is exactly the issue.

Might be good to add an example on the docs for this.
@ribalnasr to summarize 

``` javascript
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
import * as flamelink from 'flamelink/app';
import 'flamelink/content';

admin.initializeApp();
const firebaseApp = admin.app();

const flApp = flamelink({
  firebaseApp,
  dbType: 'cf',
  env: 'production',
  locale: 'en-US',
});

export const testFunction = functions.https.onRequest((request, response) => {
  ....
});

**Comment by ribalnasr** [comment]
Unfortunately this still doesn't work.

here are my packages versions:

    "firebase-admin": "^8.10.0",
    "firebase-functions": "^3.6.1",
    "flamelink": "^1.0.0-alpha.31",

and firebase-tools is version 8.6.0

what are yours?

**Comment by gitdubz** [comment]
Thanks, we will add a section to the docs for this 👍
