### ISSUE TITLE
Meta values "lastModifiedBy" and "createdBy" are always "UNKNOWN"

### ISSUE THREAD

**Issue by ribalnasr** [flamelink/flamelink-js-sdk#139]
hello :)

i noticed that when creating a document or updating it using the sdk, the **lastModifiedBy** and **createdBy** under **\_fl_meta\_** are always "UNKNOWN" even when a user is authenticated.
it is important to have the correct values here for logging and security reasons.

(Using Cloud Firestore)

**Comment by gitdubz** [comment]
Hi @ribalnasr 

I will look into it for you, which versions of firebase SDK and firebase Admin SDK are you using?
Aslo is the code executed server side or client side when adding a record?

**Comment by gitdubz** [comment]
Hi @ribalnasr I found the issue and will release an update soonest 👍

**Comment by gitdubz** [comment]
Hi @ribalnasr an updated version of the SDK has been released.

You can update the flamelink package to `1.0.0-alpha.32`, please let me know if this resolves your issue.
