### ISSUE TITLE
app.content.get do not response

### ISSUE THREAD

**Issue by RonDaha** [flamelink/flamelink-js-sdk#160]
Hey, I wanted to start using your SDK (from the browser) but cannot seems to get it to work.

I initialized flamelink app just like you showed in your docs,
when I try to - `app.content.get({schemaKey: "someKey"})`
it's just waiting forever, no error or any responses getting back. 
Also the network tab is clean seems that no HTTP request has been made at all. 
Any help here please

I am using the same firebase config credentials I use on the flamelink console.
From package.json -  `flamelink": "^1.0.0-alpha.34`

**Comment by gitdubz** [comment]
Hi @RonDaha 

Could you kindly share some code to look at?

How you are initializing the flamelink SDK and also the code you are using to retrieve the data?

**Comment by RonDaha** [comment]
Hey @gitdubz 
This is the code snippet I am using

```
const firebaseApp = firebase.initializeApp('<firebase-credentials>')
const app = flamelink({ firebaseApp })
app.content.get({ schemaKey: 'schema-key' })
    .then((res) => {
        console.log(res)
    })
    .catch((e) => {
        console.log(e)
    })
```
