### ISSUE TITLE
Send a Timestamp with the Content API to populate a Date field

### ISSUE THREAD

**Issue by leeprobert** [flamelink/flamelink-js-sdk#165]
I have a Date field in my content and am using the API to create Documents. I need to send a Timestamp through the Flamelink SDK/API and into Firebase. The Timestamp looks just great in Firestore but when Flamelink tries to parse it as a Date it crashes the field. How do I get Flamelink to see the Timestamp as a Date? Is it just a String?

**Comment by leeprobert** [comment]
I've raised a Stack ticket for this too: https://stackoverflow.com/questions/67353882/flamelink-send-timestamp-with-the-content-api

Alternatively, it would be great to add the content metadata fields to the overview table, so we can sort on fields like creationDate. We are using the Flamelink CMS as a moderation tool for the data in Firestore, so sorting on the date of creation is critical.

**Comment by gitdubz** [comment]
Hi @leeprobert 

We have added a Timestamp field a while ago for Firestore to the schema builder. 
You can have a look when editing a schema. 

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/48430891/145098795-8da6de52-a1b2-4439-80ca-a990ff3118a1.png">


<hr />

Sorting on Create and Update date is also available when toggling the options in the overview


<img width="1915" alt="image" src="https://user-images.githubusercontent.com/48430891/145099443-9ef8a426-dd56-4598-ab5f-8a250b5507a2.png">


<img width="1916" alt="image" src="https://user-images.githubusercontent.com/48430891/145099308-5be0fa33-48b1-4088-80ed-6358bb9c5783.png">
