### ISSUE TITLE
Add an actual LICENSE file

### ISSUE THREAD

**Issue by samtstern** [flamelink/flamelink-js-sdk#169]
The README says that this is MIT licensed but there is no LICENSE file that I can see and the GitHub API does not recognize the licensing:
https://api.github.com/repos/flamelink/flamelink-js-sdk (see `license: null`)

This project will be listed on https://devlibrary.withgoogle.com/ but the page won't be visible until we can detect a license.

**Comment by jasonbacon** [comment]
Hey Sam,
Thanks for checking out the submission. Just letting you know we've seen your query and will action asap and let you know.
Have a great day.

**Comment by gitdubz** [comment]
Thanks @samtstern 
I have added a LICENSE file and it is picked up 👍
