### ISSUE TITLE
SigningError when using Admin SDK and getUrl

### ISSUE THREAD

**Issue by leeprobert** [flamelink/flamelink-js-sdk#170]
I have a cloud function running to get a files URL and store it to my Document but when the function runs I get a `SigningError` like so:
`Failed to get URL: SigningError: The caller does not have permission Error`
I am using `Firebase Admin` with `Flamelink/storage`

**Comment by gitdubz** [comment]
Hi @leeprobert 

This seems related to the permissions enabled for the service account used to instantiate the admin sdk.

Can you kindly check that the service account/admin account you are using has the appropriate permissions needed for signing urls?

More info on this issue
https://github.com/googleapis/nodejs-storage/issues/1222

more specifically this
https://github.com/googleapis/nodejs-storage/issues/1222#issuecomment-649216642

Also have a look at this
https://stackoverflow.com/questions/53305784/signingerror-with-firebase-getsignedurl

**Comment by leeprobert** [comment]
Yes, I had to go into Google Cloud and add the permissions 👍
