### ISSUE TITLE
Very persistent error [FLAMELINK] The "firestore" Firebase service could not be instantiated. 

### ISSUE THREAD

**Issue by dankerk** [flamelink/flamelink-js-sdk#180]
Hi there,

I'm starting to get quite desperate to get the flamelink SDK to work. 
Can you see what's causing this error?

[FLAMELINK] The "firestore" Firebase service could not be instantiated. Please ensure you have imported the package for this service.
TypeError: context.firebaseApp[serviceName] is not a function

At this point I'm quite sure firestore is already instantiated. Any help would be greatly appreciated.
I'm using Nextjs and trying to list the pages in the console just to get the basisc to work:

```
  useEffect(() => {
    getFlamelinkApp().content.get({ schemaKey: 'page' })
    .then((pages: any) => {
      console.log('All of your pages:', pages)
    })
    .catch((error: any) => console.log(error))
  }, []);
```

```import flamelink from 'flamelink/app'
import 'flamelink/content'
import { getFirestore } from "firebase/firestore";
import { initializeApp } from 'firebase/app';
import { firebaseConfig } from '../settings/firebase.config';

const firebaseApp = initializeApp(firebaseConfig);
let flamelinkApp: any;

export function getFlamelinkApp() {
  if (!flamelinkApp) {
    getFirestore(); // attempting to make sure firestore is loaded before initialising flamelink

    flamelinkApp = flamelink({
      firebaseApp,
      env: 'production',
      locale: 'en-US',
      dbType: 'cf' // optional, defaults to `rtdb` - can be 'rtdb' or 'cf' (Realtime DB vs Cloud Firestore)
    })
  }
  return flamelinkApp;
}```

**Comment by dewetvdm** [comment]
Hi,

Which version of the Firebase SDK are you using?

Flamelink does not v9 of the Firebase SDK (modular importing)

**Comment by dankerk** [comment]
Aaaah nooo haha! Then that must be it... I'm using V9

This is my setup at the moment:  

"dependencies": {
    "@material-ui/core": "^4.12.3",
    "firebase": "^9.0.1",
    "firebase-admin": "^9.11.1",
    "flamelink": "^1.0.0-alpha.34",
    "install": "^0.13.0",
    "next": "11.1.0",
    "npm": "^7.21.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "styled-components": "^5.3.1"
  },
  "devDependencies": {
    "@types/react": "17.0.19",
    "@types/styled-components": "^5.1.13",
    "babel-plugin-styled-components": "^1.13.2",
    "eslint": "7.32.0",
    "eslint-config-next": "11.1.0",
    "generate-react-cli": "^7.0.4",
    "sass": "^1.38.1",
    "typescript": "4.4.2"
  }

**Comment by dewetvdm** [comment]
Can you install Firebase SDK v8

npm i --save firebase@8.10.0 

and then follow this guide?

https://flamelink.github.io/flamelink-js-sdk/#/getting-started?id=creating-your-flamelink-app-instance

**Comment by dankerk** [comment]
That made all the difference! Thanks a lot.
