### ISSUE TITLE
Can't set Workflow Status (Draft / Review / Publish) via API

### ISSUE THREAD

**Issue by ptreitler** [flamelink/flamelink-js-sdk#183]
I want to add data to Flamelink in the "Draft" status in my app, but I haven't found a way to do so using the API.
I can read the status on my data just fine via `_fl_meta_.status`, but there doesn't seem to be a way to set this attribute in `flamelinkApp.content.add`.

I have tried passing it as part of the data:
```
flamelinkApp.content
      .add({
        schemaKey: "mySchema",
        data: {
          _fl_meta_: {
            status: "draft",
          },
         // ...
        },
      })
```
...but this seems to get ignored as it doesn't show up in the CMS or the Cloud Firestore.

**Comment by gitdubz** [comment]
Hi @ptreitler 

A new version of the sdk has been released (1.0.0-rc.1)

You can update or install the latest (npm install flamelink@next)

https://flamelink.github.io/flamelink-js-sdk/#/content?id=add

you will notice the new `status` parameter that can be passed

```
 app.content.add({
  schemaKey: 'blogPost',
    data: {
      title: 'New Post',
    },
    status: 'draft',
 })
```
