### ISSUE TITLE
Images returned as DocumentReference

### ISSUE THREAD

**Issue by dankerk** [flamelink/flamelink-js-sdk#184]
Hi there,

I'm trying to get and display images uploaded through Flamelink, but they are returned to me as an array of DocumentReferences.

How can I get their urls?

```
headerImage: [
    DocumentReference {
      firestore: [Firestore],
      _delegate: [DocumentReference$1],
      _userDataWriter: [UserDataWriter]
    }
  ],
```

**Comment by dewetvdm** [comment]
Hi @dankerk 

The correct documentation is here: https://flamelink.github.io/flamelink-js-sdk/#/content

The link posted in your original question was for the old SDK

as for the document reference, you can use the populate function to populate images and relational data
https://flamelink.github.io/flamelink-js-sdk/#/content?id=get-examples

**Comment by dewetvdm** [comment]
examples 
```
app.content.get({ 
  schemaKey: 'page', 
  populate: ['headerImage'] 
})
```

**Comment by dankerk** [comment]
Thanks @dewetvdm !

That leads me to another interesting "issue"/topic..

```
The Firebase client-side SDK cannot access the Storage Bucket server-side.
Please use the admin SDK instead - https://www.npmjs.com/package/firebase-admin
```

So I switched to the admin sdk, but then it throws:

```
error - ./node_modules/@google-cloud/storage/build/src/bucket.js:21:0
Module not found: Can't resolve 'fs'

Import trace for requested module:
./node_modules/@google-cloud/storage/build/src/index.js
./node_modules/firebase-admin/lib/storage/storage.js
./node_modules/firebase-admin/lib/firebase-namespace.js
./node_modules/firebase-admin/lib/default-namespace.js
./node_modules/firebase-admin/lib/index.js
./src/utils/flamelink.ts
./src/pages/index.tsx
```

Did you encounter that before?

I did manage to log out the object for the headerImage, but when I try to use it throws:
`SerializableError: Error serializing `.page.headerImage` returned from `getStaticProps` in "/page/[slug]".`

It seems I would need to get rid of some of the object data. Is this familiar to you?

**Comment by dewetvdm** [comment]
@dankerk are you running this code server side (example static site generator (gatsby, scully) or nextjs with static/serverside queries etc)?

If so then you will need to make that you initialize the SDK with the correct package 
serverside will require the firebase-admin-sdk and client side the normal web SDK which you seem to be using at the moment)

and easy wat too check is 
```
// server does not have a window object so will be undefined
if (typeof window === 'undefined') { 
 // initialize flamelink with the firebase admin SDK (node SDK)
} else {
 // initialize the flamelink SDK with the firebase web SDK 
}
```

**Comment by dankerk** [comment]
My bad. The issue was a mistake on my end.

I had this in my code:

```
HomePage.getInitialProps = async () => {
// some firebaseAdmin code here...
```

But getInitialProps (especially when appended to the homepage class) runs on the client side so I had to replace it with:

```
export async function getStaticProps() {
// some firebaseAdmin code here...
```

**Comment by dankerk** [comment]
Thanks for the support @dewetvdm 

For anyone reading this who is running into parsing issues from nextjs like this one:
`Error serializing ... cannot be serialized as JSON. Please only return JSON serializable data types.`

Wrapping this around the response fixes it:

`JSON.parse(JSON.stringify(responseData));`
