### ISSUE TITLE
dyld[15631]: missing symbol called

### ISSUE THREAD

**Issue by moschan** [flamelink/flamelink-js-sdk#185]
When I run the app using Intel chip mac, it works, however when I run the app by Apple M1, it cause error when I open http://localhost:3000.

It seems when I use `content.get` with `populate: [ "SOME_IMAGE_FIELD" ]` causes error.
Without  `populate: [ "SOME_IMAGE_FIELD" ]` , it works well

## versions
```
    "next": "12.0.4",
    "firebase": "^8.6.8",
    "firebase-admin": "^9.10.0",
    "flamelink": "^1.0.0-alpha.34",
```

## Error message when I open localhost
```
dyld[15631]: missing symbol called
error Command failed with signal "SIGABRT".
```

**Comment by dewetvdm** [comment]
Hi @moschan 

Can you please ensure firebase < v9 is installed?
"firebase": "^8.6.8" could install v9

**Comment by moschan** [comment]
Yes, I'm using v8

Do you have a prefer version of firebase-admin?

**Comment by moschan** [comment]
Once I delete `fast-crc32c` from dependencies it resolved.

>    "fast-crc32c": "^2.0.0",
