### ISSUE TITLE
Filter content.subscribe() query by field value as an alternative to query.where(fieldName, '==', value) in Firestore.

### ISSUE THREAD

**Issue by ribalnasr** [flamelink/flamelink-js-sdk#53]
Is there a way in the current version to filter the results received in content.subscribe() as an alternative to 

`query => query.where('project', '==', _SomeDocumentRef_) 
`
in Firestore and AngularFire?

maybe something like this (which i tried):
```
content.subscribe({
    schemaKey: 'stories',
    filter: ['project', '==', _SomeDocumentRef_ ]
    callback: (error, data) => { ... }
})
```

**Comment by ribalnasr** [comment]
just figured out the solution,

its "filters" not "filter", and the value is an Array of Arrays like this:

```
content.subscribe({
    schemaKey: 'stories',
    filters: [['project', '==', _SomeDocumentRef_ ]]
    callback: (error, data) => { ... }
})
```

great work! :)

**Comment by jperasmus** [comment]
Glad you got it. Using the array of arrays gives you the ability to apply as many filters as you'd like to your queries.
