### ISSUE TITLE
FirebaseError: Function WriteBatch.delete() requires its first argument to be a DocumentReference, but it was: a custom QueryDocumentSnapshot object

### ISSUE THREAD

**Issue by ribalnasr** [flamelink/flamelink-js-sdk#55]
looks like am gonna stick around for a while... :)

```
content.remove({
	schemaKey: "_schema_",
	entryId: "_id_",
})

```
is giving this error:
`FirebaseError: Function WriteBatch.delete() requires its first argument to be a DocumentReference, but it was: a custom QueryDocumentSnapshot object.
`

note: i'm only testing with cloud firestore not rtdb.

**Comment by jperasmus** [comment]
haha, cool, I'll take a look.

**Comment by ribalnasr** [comment]
Also getting an error when trying to add:

```
content.add({
	schemaKey: 'channels',
	data: {name: 'test'}
});
```

Error: Uncaught (in promise): FirebaseError: [code=invalid-argument]: Function DocumentReference.set() called with invalid data. Unsupported field value: a custom Query object (found in field _fl_meta_.schemaRef)
FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: a custom Query object (found in field _fl_meta_.schemaRef)

**Comment by jperasmus** [comment]
`v1.0.0-alpha.10` is now available that should address these 2 issues.

**Comment by ribalnasr** [comment]
remove() now works,
add() works however:
1) it doesn't add locale to _fl_meta_ which i believe is the reason why it doesn't show in the cms not in the .get() and .subscribe()
2) the promise returns undefined, returning the id of the document would be great!

**Comment by jperasmus** [comment]
You are absolutely right, the `locale` is missing. I'll fix that.

I like the idea of returning the new doc ID. If possible, I might take that a step further and return the whole document object. It is just important for us to have the API's for RTDB and CF to behave in the same way.

**Comment by jperasmus** [comment]
Can you try `v1.0.0-alpha.11` please? It should fix the missing `locale` issue when adding an entry and it should now return the whole doc entry payload for the Promise response.
