### ISSUE TITLE
storage.upload() FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: a custom CollectionReference object (found in field folderId)

### ISSUE THREAD

**Issue by ribalnasr** [flamelink/flamelink-js-sdk#59]
hello!
new day, new issues 😄 

using storage.upload(file, {}) with no custom options is resulting in the following error:

`FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: a custom CollectionReference object (found in field folderId)
`

which i believe is related to previously solved issue:  https://github.com/flamelink/flamelink-js-sdk/issues/55

(always using cloud firestore.)

**Comment by jperasmus** [comment]
hi, thanks, I'll take a look at this one

**Comment by jperasmus** [comment]
What are you using as the `file` variable in your scenario?

**Comment by ribalnasr** [comment]
Client-side for now.

I'm using a regular `<input type="file" />` which gives me a **FileList**. and for each **File** inside it i call the upload function: `flamelink.storage.upload(fileList.item(0), {})`

It seems that the file is being uploaded but the error occurs later when saving to the database.

**Comment by jperasmus** [comment]
Thanks for the info. Can you try `v1.0.0-alpha.12` please to see if that solves this for you?

**Comment by ribalnasr** [comment]
Like a charm,

However i wish it would return the DocumentRef from the **fl_files** collection,
for now i can get it like this:

```
flamelink.storage.upload(file, {}).then(
	success => {
		const ref = this.flamelink.storage.fileRef(success.metadata.customMetadata.flamelinkFileId)
	}
);
```

_success.metadata.customMetadata.flamelinkFileId_ is the shortest way  i found to get the fileID.
And the success.ref object does not return a DocumentRef.

**Comment by jperasmus** [comment]
I'll see what I can do here. The reason we expose the file and folder ID in the metadata is exactly for this reason, but it was easier to work with when it was just the Realtime DB. The response from this `upload` method is an `UploadTask` object that is similar to a Promise but has extra functionality so that you can determine upload progress, etc. I would not want to lose that. 

What makes it a bit trickier is that there are 2 parts to the upload: uploading the file to the Cloud Storage Bucket and also writing it to the relevant database (RTDB or CF). Maybe a good idea would be to return an object with the `UploadTask` as well as the newly created File object in the DB. Would that help you?

**Comment by jperasmus** [comment]
`v1.0.0-alpha.14` now returns the database file object and not the upload task object anymore, since it was not working as intended in any case.

**Comment by jperasmus** [comment]
Another user really needed progress events to be triggered for the uploads, so this method now returns a `PromiseEmitters` instead of a plain `Promise`.

https://flamelink.github.io/flamelink-js-sdk/#/storage?id=progress-events

**Comment by ribalnasr** [comment]
Hi again! 
this issue seems to be happening again with version flamelink@1.0.0-alpha.25

**Comment by ribalnasr** [comment]
any updates? were you able to reproduce the issue?

**Comment by jperasmus** [comment]
Apologies, I haven't had time to look into this yet. I'm a bit busy with the changes required for EU billing regulations but will take a look as soon as I can.

**Comment by ribalnasr** [comment]
hi again,
this is a very important issue as all our file uploads stopped working. i really wish you could take some time to fix it again.

**Comment by charbelalkazzi** [comment]
any updates? its happening with me as well.

**Comment by jperasmus** [comment]
Looking into this now. As a workaround, try setting a `folderId` in the upload options.

**Comment by jperasmus** [comment]
Please check out `v1.0.0-alpha.26`

**Comment by ribalnasr** [comment]
working :)
