### ISSUE TITLE
flamelink.users.addToDB - TypeError: api.ref(...).set is not a function

### ISSUE THREAD

**Issue by ribalnasr** [flamelink/flamelink-js-sdk#61]
Don't hate me!

```
flamelink.users.addToDB({
	uid: '_USER_ID_'
	data: {}
});
```

returns this error: `TypeError: api.ref(...).set is not a function`.

(always using Cloud Firestore)

**Comment by jperasmus** [comment]
hahaha, not at all, I appreciate you picking up these things. I'll take a look

**Comment by charbelalkazzi** [comment]
any update concerning this issue? I'm experiencing the same problem

**Comment by jperasmus** [comment]
Fix should now be available in `v1.0.0-alpha.13`

**Comment by ribalnasr** [comment]
just tested it! works great.
