### ISSUE TITLE
Difference to other Flamelink js SDK

### ISSUE THREAD

**Issue by SamuelSaltzmann** [flamelink/flamelink-js-sdk#62]
Hi there, 
I wanted to ask, why there is a second repository for a flamelink js SDK?
https://github.com/flamelink/flamelink
https://github.com/flamelink/flamelink-js-sdk/

What is going to be the main difference?
I am confused and do not know which of those two will be the one that works in the future?

Why is there one in beta and one in alpha and the one in alpha seems to be the one that’s currently maintained. Is the one in beta mode going to be updated or can’t I trust that it will be improved and fixed in the future?
And what about this one here? 
I am confused.

**Comment by jperasmus** [comment]
Hi there,

Apologies for the confusion, I will explain.

The repo you see at https://github.com/flamelink/flamelink is the current SDK that only supports the Firebase Realtime Database. It is an oversight on our end to still have the `beta` message on the README (I will remove that today). When installing from NPM (`npm i flamelink`), you get that repo's code.

This repo you commented on (`flamelink-js-sdk`) is the newer version that supports both the RTDB as well as Cloud Firestore. Any new features will be added to this repo. Where necessary, bugfixes will still be made to the current SDK for the foreseeable future. You can install this new `alpha` SDK with `npm i flamelink@next`.

Differences between the two libraries can be seen if you look at the [migration guide](https://flamelink.github.io/flamelink-js-sdk/#/migration-guide) from the current (`v0.x`) to this new (`v1.x`) SDK.

I hope that clears it up. Please ask if you have any other questions and I'd be happy to clarify them.

**Comment by SamuelSaltzmann** [comment]
Hi there,

thank you very much for that clear answer. I just saw the migration guide and except from the change from "set" to "add"/"update" it should be a piece of cake to migrate the project later on.

Best regards!
