### ISSUE TITLE
Feature request: folders creation

### ISSUE THREAD

**Issue by vkammerer** [flamelink/flamelink-js-sdk#65]
Hello Flamelink team,

I'm sorry if this is the wrong place for a feature request. If issues should be used only for bug reports, please point me to the right place for a request.

I would like to be able to create media folders via the API. Is this something already planned that will come later, or isn't it planned at all?

Thank you

**Comment by jperasmus** [comment]
Hello @vkammerer 

Thanks for your request. This is not something that is currently planned, but we're not against it. I can't currently give you an idea of how long it would take for us to implement this, but if you feel inspired, you can contribute a PR to add it. It would be a method that lives on the `storage` namespace, like `storage.addFolder({ folderName: 'The Name', parentId: '<id of parent folder or 0>' })`

It is important that any methods are available for both the realtime DB as well as Firestore.

**Comment by vkammerer** [comment]
Thank you for your reply @jperasmus.

Unfortunately I won't have the time to implement it myself. Is there any page that list the roadmap for this library and the features it intends to implement? I couldn't find it.

As a side note regarding the Flamelink product itself: I don't know where files management sits in the features prioritization, but I feel that the file explorer could be given a bit more love (for example, the folders are not ordered alphabetically, which makes managing large amounts of files / folders almost impossible).

**Comment by jperasmus** [comment]
The development for this SDK is mostly user-driven, meaning features are added as requested by users.

For the file explorer in the app itself: there is a complete overhaul planned, but I cannot give you an exact date for when that will be available. There are currently other features taking priority, so if I would have to give an educated guess, I would say it will most likely only be done towards the end of this year.
