### ISSUE TITLE
updating document after changing locale, creates a new document not linked to the original document.

### ISSUE THREAD

**Issue by ribalnasr** [flamelink/flamelink-js-sdk#76]
hi,

here's my issue for the day :)

i have a case where users can create announcements, and they can add translations to them.
so the process goes as follows:
```ts
settings.setLocale('en-US');
content.add({
    schemaKey: 'announcements',
    data: { content: 'SOME_ENGLISH_TEXT'}
})
```
this will add the announcement to her/his announcements list with these buttons for each one:
**Edit English** and **Edit Arabic**

when the user clicks on Edit Arabic, we change the locale: ```settings.setLocale('ar')``` and then take the user to a form to update the content.

 the user will update the form and hit save which will run
```ts
content.update({
    schemaKey: 'announcements',
    entryId: 'yBH4nnhZrBXEfFaXMZHU' // ID retrieved from the en-US version
    data: { content: 'SOME_ARABIC_TEXT'}
))
```

in this case the Arabic version was still not present on update, so we get the following warning:
```
[FLAMELINK] No entry existed for schema "announcements" with ID "yBH4nnhZrBXEfFaXMZHU" - creating new entry instead.
```
**and the new document created in arabic is not related to the english version.**

**What i expect to happen** in this case, is that the newly created document should have an 
 _\_fl_meta\_.fl_id_ equal to the _entryId_ sent with the content.update(...).

**Comment by jperasmus** [comment]
hi, this is a nice one :)

I can see your use case and it makes total sense to me. I'll have to give a bit more thought as to how we need to handle it in the SDK to resemble what happens in the app as close as possible.

The app works like this:
* You have one locale set as the default locale, which we use as the source of truth, meaning, there should always be a document for each entry made for the default locale, even if it is almost empty.
* Adding an entry for the default locale does not else, just that
* Adding an entry for a non-default locale, adds that entry and also the "empty" entry for the default locale

If we want to stick to this flow, we would need to ensure that the SDK checks the available locales as well as whether the current one is the default or not.

**Comment by jperasmus** [comment]
Hi @ribalnasr just letting you know, I haven't forgotten about this issue, I've been travelling and focusing on other features within the app, but I am going to try and make time this week to look at this one.

**Comment by ribalnasr** [comment]
great to hear! this will be very useful.

(on another note, i'm planing on working soon on some functions for firestore rules to automatically implement the rules from the fl_permissions collection. unless your team already started working on something similar)

**Comment by jperasmus** [comment]
That sounds great! I still have an outstanding task to write some documentation around how to do that for Firestore (have a similar article for the Realtime DB), but I haven't gotten to it. Would be great to see your work on this.

**Comment by ribalnasr** [comment]
Hello!
Concerning the rules, please check this issue https://github.com/flamelink/flamelink-js-sdk/issues/86,

As for the initial topic of this thread, any update on this?

**Comment by jperasmus** [comment]
Hi @ribalnasr 

Apologies that it took me so long to give this attention. I've made some changes in `v1.0.0-alpha.22` that will handling adding and updating of content in the SDK to be similar to how it is handled in-app at the moment, namely:

- when adding an entry using a non-default locale, a placeholder entry for the default locale will automatically be created with the same `_fl_meta_.fl_id`.
- when adding an entry for a default locale, it will simply create it as-is and not do anything for non-default locales
- when updating an entry and the entry does not exist for the current locale, a new entry will be created while keeping the provided `entryId` (this was not previously kept)

When you get a moment, can you please check this release to see if it works for your needs?

**Comment by ribalnasr** [comment]
This now works as expected.
